
version: 0.0
os: linux
files:
  - source: .
    destination: /opt/carnibot
hooks:
  AfterInstall:
    - location: scripts/install_pexed_binary.sh
      runas: root
  ApplicationStop:
    - location: scripts/stop_application.sh
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      runas: root
