
version: 0.0
os: linux
files:
  - source: carnibot
    destination: /usr/local/bin
  - source: .
    destination: /opt/carnibot
hooks:
  AfterInstall:
    - location: scripts/migrate_database.sh
  ApplicationStop:
    - location: scripts/stop_application.sh
  ApplicationStart:
    - location: scripts/start_application.sh
