
version: 0.0
os: linux
files:
  - source: carnibot
    destination: /usr/local/bin
hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
  ApplicationStart:
    - location: scripts/start_application.sh
